# Generated by Django 5.0.4 on 2024-04-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=55)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
