# Generated by Django 5.0.4 on 2024-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contain',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contain',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
